### ISSUE TITLE
it is not recognizing me bro

### ISSUE THREAD

**Issue by abdullaevich700** [medsriha/real-time-face-recognition#4]
i runned each python file and at the end i am running face_recognizer.py but is is not recognizing me

**Comment by medsriha** [comment]
@abdullaevich700 You could increase the number of pictures taken from 30 to 50, for example. Try to move your head to increase slightly while taking the pictures; this will increase the variability and could improve the performance. Or you could change the model to a better one.

**Comment by medsriha** [comment]
No update. Closing the issue
