### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Not0a0developer** [medsriha/real-time-face-recognition#6]
<img width="890" alt="image" src="https://github.com/user-attachments/assets/9da12e57-fcab-4524-8269-bd424f4b275e">

**Comment by Not0a0developer** [comment]
@medsriha it doesnt work for me because of this error in face_taker.py

**Comment by Not0a0developer** [comment]
fixed it, however we still have this
<img width="953" alt="image" src="https://github.com/user-attachments/assets/b5956668-36e6-48a8-9632-a57a93eba903">
*btw im on mac os X sequoia

**Comment by medsriha** [comment]
Hi @Not0a0developer, do you mind sharing your code so I can replicate the issue?

**Comment by Not0a0developer** [comment]
it was just an issue with the XML file which was in a file corrupti9on;; re
downloaded it and its fixed
